apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ekart-deployment
spec:
  selector:
    matchLabels:
      app: ekart
  replicas: 2 
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart
          image: narsi23/ekart:5
          ports:
            - containerPort: 8070 
